### ISSUE TITLE
`initSubscriber` returning `subscribe` api (?)

### ISSUE THREAD

**Issue by ramonvictor** [ivantsov/redux-subscriber#1]
Hi there! First of all, very nice idea, thanks for implementing this module! Pretty simple implementation and quite useful.

I was curious to know whether you considered returning `subscribe` api when calling `initSubscriber`.
See following example:

```js
import {createStore} from 'redux';
import initSubscriber from 'redux-subscriber';

const store = createStore(...);
const subscriber = initSubscriber(store);

subscriber.subscribe('user.messages.count', state => {
    // do something
});
```

I think that makes it very clear from where the `subscribe` method come from.

**Comment by ivantsov** [comment]
Hi @ramonvictor. Thanks for your interesting in the project.

Actually, I hadn't had such plan before, but if you think it could make usage of the package more obvious, then yeah, I'll do it. And, of course, feel free to make a PR! 
Anyway, thanks for the idea :)

**Comment by ramonvictor** [comment]
@ivantsov thanks for implementing the suggestion! Appreciated! :)

**Comment by ivantsov** [comment]
@ramonvictor no problem :)
