### ISSUE TITLE
Subscribe handler being fired twice for one change

### ISSUE THREAD

**Issue by shennan** [ivantsov/redux-subscriber#12]
Subscribe callback is being fired twice when there is only one state change.

Code here:

```
import Subscriber from 'redux-subscriber'
import store from './my-store'

const subscribe = Subscriber(store)

subscribe('org.selected', state => {

  console.log('RENDERING', 'org.selected') // this is being output twice per state change

  renderSelection(state)

})
```

Can you think of a reason that the handler may be fired twice with only one action dispatched? Perhaps I'm missing something?

Note that when I comment out the **redux-subscriber** code and use the normal `store.subscribe` method, it works as expected; the output shows once per action. Is it possible the subscriber is changing the way the store dispatches?

**Comment by shennan** [comment]
Ok, I believe I've worked out what the problem is. In a separate file I'm also calling `Subscriber()` on the same store, as two of my components are interested in the same area of state.

This is a problem because this library calls `store.subscribe()` each time a 'subscriber' is initiated. Because the stored subscription keys are a singleton, all subscription key updates are being dispatched with each subscribe handler call, regardless of whether the subscriber has been instantiated from a different area of the application.

Can I propose we create per-subscriber subscription key stores? Effectively creating a new store of keys each time the subscriber is initialised so as to get rid of this singleton:

https://github.com/ivantsov/redux-subscriber/blob/3bd43de5c0d46b9bb14d9a7ad80573f7244b2343/src/index.js#L3

Would you accept a PR to this effect?

**Comment by ivantsov** [comment]
Why do you wanna initialize redux-subscriber twice? You can use [`subscribe`](https://github.com/ivantsov/redux-subscriber#subscribekey-callbackfunction---subscribe-callbackfunction-to-changes) to avoid the problem you described.

**Comment by shennan** [comment]
I see now the use of subscribe - thanks for the clarification. Of course, that means that the store must be initiated first with an `initSubscriber` call from your library at a lower level in the code base.

I guess I would prefer a less-integrated approach. With the current scenario I have to initialise my store with your library at controller level, and then use the subscribe in my components modules, assuming that the store has been instantiated with a subscriber elsewhere in my codebase. For me it's preferable to let each of my modules instantiate their own subscriber libraries and not have to use the library at such a low level.

But I understand if there is no appetite for this approach. I'll close the issue.

**Comment by ivantsov** [comment]
Glad that we found a solution.
Also I got your point, however even with `redux` & `react-redux` you have to create store in one place and only after that you can use `connect` for components. Basically, same approach works for `redux-subscriber`.
